#!/bin/sh

echo "\n\n\n\n========= deleting postgres database ===========================================\n\n";


ME=$(whoami)
echo $ME
source .environment-v90

postgresql.v90 start

sleep 5

psql -U "$ME" -d template1 << EOF
\list
Drop database alfresco;
CREATE DATABASE alfresco WITH OWNER alfresco;
\list
EOF

echo "========= created postgres database ===========================================\n\n";

echo "========= deleting /opt/local/alfresco/alf_data ===========================================\n\n";

rm -R /opt/local/alfresco/alf_data/*

echo "========= alfresco refresh is done ===========================================\n\n\n\n";
